# name: Web, Android, iOS Build

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     name: Web, Android, iOS Build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Upload binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.WORKFLOW_TOKEN }}
#           file: zzz_release/yyyy/
#           asset_name: mything
#           tag: ${{ github.run_number }}
#           overwrite: true
#           body: "This is my release text"

name: Releases

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "zzz_release/*"
          # artifacts: "build/app/outputs/flutter-apk/app-release.apk, build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk, build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
