name: Android, iOS, Web Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Android, iOS, Web Build

    env:
      github_token: ${{secrets.WORKFLOW_TOKEN}}
      github_repo: sabikrahat/github_workflow_flutter_project.git
      git_user_email: sabikrahat72428@gmail.com
      git_user_name: Md. Sabik Alam Rahat
      release_tag: v1.0.${{github.run_number}}

    # This job will run on macos virtual machine
    runs-on: macos-latest

    steps:
      - name: Checkout code

        run: |
          echo "Github Repo is ${{ env.github_repo }}"
          echo "Github Repo Token is ${{ env.github_token }}"
          echo "Git User Email is ${{ env.git_user_email }}"
          echo "Git User Name is ${{ env.git_user_name }}"
          echo "Release Tag is ${{ env.release_tag }}"

        # Checkout the repository
        uses: actions/checkout@v3

      # Setup Java environment.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18.x"

      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.3.2"

      - run: flutter config --enable-android
      - run: flutter config --enable-ios
      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get

      # Flutter android apk build command.
      - run: flutter build apk
      - run: flutter build apk --split-per-abi

      # Flutter ios ipa build command.
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Flutter web release command.
      - run: flutter build web --web-renderer html --release
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines
          git config --global user.email $git_user_email
          git config --global user.name $git_user_name
          git status
          git remote add origin https://$github_token@github.com/$github_repo
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f

      # Upload assets to release
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*,build/ios/iphoneos/app.ipa"
          tag: $release_tag
          token: $github_token
