name: Temp Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "text.txt"
          bodyFile: "body.md"
          tag: "*"
          # tag: ${{ github.run_number }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
