name: Web, Android, iOS Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Web, Android, iOS Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.WORKFLOW_TOKEN }}
          file: "zzz_release/yyyy/*, zzz_release/xxxx/*"
          asset_name: mything
          tag: ${{ github.run_number }}
          overwrite: true
          body: "This is my release text"
